name: ci

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12"]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip" # pip cache for faster installs

            - name: Upgrade pip
              run: python -m pip install --upgrade pip

            - name: Install test deps
              run: |
                  pip install pytest pytest-cov coverage

            - name: Install package (if present)
              run: |
                  # Won't fail the build if package metadata isn't ready yet
                  pip install -e ".[dev]" || true

            - name: Run tests with coverage
              run: |
                  pytest -q --cov=football_script --cov-report=xml --cov-report=term

            - name: Upload coverage.xml
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-${{ matrix.python-version }}
                  path: coverage.xml
